### ISSUE TITLE
Setup and configure facilities for data management layer

### ISSUE THREAD

**Issue by lelouvincx** [TinhHoaSolutions-EzHR/chatbot#35]
As a team member of both chatbot-core and vanphongso,
I need the data management layer facilities to be stable as soon as possible. So that I can continue developing backend and frontend.

For both environments: development and production.

## Tasks
- [ ] Document Storage (AWS S3 or MinIO)
- [ ] Vector Database (Qdrant)
- [ ] Relational Database (SQL Server)
